### ISSUE TITLE
match work-around for coastlines from js version

### ISSUE THREAD

**Issue by ghost** [okdistribute/osm-is-area.rs#1]
There are some islands that disappear during rendering without this patch:

https://github.com/mk30/osm-is-area/commit/5510c1e7221acddebce8d67926ff62bdb530a174

**Comment by okdistribute** [comment]
OK fix is in! https://github.com/okdistribute/osm-is-area.rs/commit/5621437040f5a590dec31932b83b3017dcea0be6

**Comment by okdistribute** [comment]
published in 0.1.4
